"""
Deep Learning Classifier Training Pipeline
Author: Meet Ahalpara

This module serves as the terminal training pipeline for the 4-class NLP sentiment 
classifier. It systematically ingests preprocessed corporate datasets, translates 
raw textual data into numerical tensor sequences via Tokenization, and compiles 
a multi-layered Sequential neural network utilizing Embedding and GlobalAveragePooling1D 
architectures. The system autonomously evaluates its predictive performance and 
serializes the final artifacts for future deployment.
"""
import os
import re
import random
import numpy as np
import pandas as pd

print("\n[INFO] Initializing TensorFlow framework and accelerating backend drivers...")
import tensorflow as tf
print("[SUCCESS] TensorFlow Core successfully initialized.")

import matplotlib.pyplot as plt

random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)

print("\n" + "="*65)
print(" NLP DEEP LEARNING CLASSIFIER TRAINING PIPELINE INITIATED")
print("="*65)

# ==========================================
# PHASE 1: ENVIRONMENT & PATH RESOLUTION
# ==========================================
print("\n[INFO] Resolving directory paths and validating target datasets...")
# Dataset paths are dynamically resolved to ensure strict environment agnosticism.
project_folder = os.path.dirname(os.path.abspath(__file__))
final_dataset_folder = os.path.join(project_folder, "Dataset", "FinalDatasets")

train_path = os.path.join(final_dataset_folder, "final_train.csv")
test_path = os.path.join(final_dataset_folder, "final_test.csv")

if not os.path.exists(train_path):
    raise FileNotFoundError(f"Train file not found: {train_path}")

if not os.path.exists(test_path):
    raise FileNotFoundError(f"Test file not found: {test_path}")

print("[SUCCESS] Environment resolved and validation complete.")

# ==========================================
# PHASE 2: DATA INGESTION
# ==========================================
print("\n[INFO] Ingesting stratified training and evaluation partitions...")
# The stratified CSV matrices generated by the stratification layer are loaded into memory.
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

print(f"[SUCCESS] Dataset partitions successfully loaded.")
print(f"|-- Training Matrix Shape   : {train_df.shape}")
print(f"|-- Evaluation Matrix Shape : {test_df.shape}")

print("\n[PREVIEW] Training Data Structure (Sample View):")
print("-" * 65)
print(train_df.head())
print("-" * 65)

# ==========================================
# PHASE 3: TEXT SANITIZATION & LABEL MAPPING
# ==========================================
print("\n[INFO] Applying secondary sanitization and target label encoding...")

def clean_text(text):
    """
    Rigorous text sanitization to ensure perfect alignment with the preprocessing 
    distributions utilized during initial corpus generation.
    
    Args:
        text (str): Raw input text.
        
    Returns:
        str: A lowercased string rigorously stripped of HTML markup, non-alphanumeric 
             characters, and irregular whitespace distributions.
    """
    text = str(text).lower()
    text = re.sub(r"<br\s*/?>", " ", text)  # Replace HTML line breaks with space 
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text) # Remove special characters, keep only letters, numbers, and spaces
    text = re.sub(r"\s+", " ", text).strip() # Replace multiple spaces with a single space and trim leading/trailing spaces
    return text

train_df["text"] = train_df["text"].apply(clean_text)
test_df["text"] = test_df["text"].apply(clean_text)

# The deterministic label-to-integer mapping is established.
# This is mathematically essential for mapping softmax probability distributions 
# back to human-readable strings during the final inference testing phase.
label_to_index = {
    "negative": 0,
    "positive": 1,
    "mixed": 2,
    "neutral": 3    
}

index_to_label = {v: k for k, v in label_to_index.items()}

train_df["label_id"] = train_df["sentiment"].map(label_to_index)
test_df["label_id"] = test_df["sentiment"].map(label_to_index)

if train_df["label_id"].isnull().any():
    raise ValueError("Some training labels are invalid. Check the 'sentiment' column in final_train.csv.")

if test_df["label_id"].isnull().any():
    raise ValueError("Some testing labels are invalid. Check the 'sentiment' column in final_test.csv.")

x_train_text = train_df["text"].tolist()
x_test_text = test_df["text"].tolist()

# One-hot encoding is applied to the target labels. This representation is strictly required 
# for the categorical_crossentropy loss function in a multi-class setting.
y_train = tf.keras.utils.to_categorical(train_df["label_id"], num_classes=4)
y_test = tf.keras.utils.to_categorical(test_df["label_id"], num_classes=4)

print("[SUCCESS] Text matrices sanitized and labels categorically encoded.")
print(f"|-- Detected Class Map: {label_to_index}")

# ==========================================
# PHASE 4: TOKENIZATION & SEQUENCE PADDING
# ==========================================
print("\n[INFO] Initializing vocabulary tokenization and sequence padding...")

# Core hyperparameters governing the natural language processing dimensions.
vocab_size = 10000
max_length = 120
oov_token = "<OOV>"

# Initialize Tokenizer to map words to integer IDs based on frequency.
# The OOV token ensures robustness against unseen words in future inference queries.
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=vocab_size, oov_token=oov_token)
tokenizer.fit_on_texts(x_train_text)

# Raw text arrays are translated into sequential integer tensor matrices.
x_train_seq = tokenizer.texts_to_sequences(x_train_text)
x_test_seq = tokenizer.texts_to_sequences(x_test_text)

# Array lengths are mathematically standardized via post-padding and post-truncating.
# Deep learning models require homogeneous tensor shapes for matrix operations.
x_train = tf.keras.preprocessing.sequence.pad_sequences(
    x_train_seq, maxlen=max_length, padding="post", truncating="post"
)
x_test = tf.keras.preprocessing.sequence.pad_sequences(
    x_test_seq, maxlen=max_length, padding="post", truncating="post"
)       

print("[SUCCESS] Sequential tokenization completed.")
print(f"|-- Standardized Training Tensor Shape   : {x_train.shape}")
print(f"|-- Standardized Evaluation Tensor Shape : {x_test.shape}")

# ==========================================
# PHASE 5: NEURAL NETWORK ARCHITECTURE
# ==========================================
print("\n[INFO] Compiling Sequential Neural Network architecture...")
# The neural network topological architecture is defined.
# Modern Keras > 3.0 uses layers.Input explicitly rather than the deprecated input_length arg.
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(max_length,), name="Tokenized_Sequence_Input"),
    tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=32, name="EmbeddingLayer"),
    tf.keras.layers.GlobalAveragePooling1D(name="PoolingLayer"),
    tf.keras.layers.Dense(32, activation='relu', name="1stReluHiddenLayer"),
    tf.keras.layers.Dense(16, activation='relu', name="2ndReluHiddenLayer"),
    tf.keras.layers.Dense(4, activation='softmax', name="SoftmaxOutputLayer")
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

print("-" * 65)
model.summary()
print("-" * 65)

# ==========================================
# PHASE 6: MODEL TRAINING & CONVERGENCE
# ==========================================
print("\n[INFO] Initiating deep learning training phase (10 Epochs)...")

# The model is fitted onto the training matrices, retaining 20% for continuous validation tracking.
history = model.fit(
    x_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

# ==========================================
# PHASE 7: SYSTEM EVALUATION & METRICS
# ==========================================
print("\n[INFO] Evaluating trained architecture against the withheld test partition...")

# Final metrics are mathematically extracted against the strictly withheld testing  
# split to evaluate the model's true structural generalization capacity.
test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=0)

print(f"[SUCCESS] Baseline Model Test Accuracy : {test_accuracy * 100:.2f}%")
print(f"[SUCCESS] Baseline Model Test Loss     : {test_loss:.4f}")

# ==========================================
# PHASE 8: VISUAL PERFORMANCE TRACKING
# ==========================================
print("\n[INFO] Rendering historical convergence trajectories (Close window to continue)...")

# Training versus Validation metrics are rendered to visually diagnose underfitting or overfitting trends.
plt.figure(figsize=(8, 5))
plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# PHASE 9: CUSTOM INFERENCE TESTING
# ==========================================
print("\n[INFO] Executing inference testing on custom out-of-sample string arrays...")

custom_reviews = [
    "the movie was released in 2020",
    "the acting was amazing",
    "the plot was confusing",
    "the visuals were beautiful but the ending was disappointing",
    "the film has several main characters",
    "the movie was boring",
    "the soundtrack was excellent",
    "the pacing was slow however the acting was strong",
    "the story takes place in a small town",
    "the dialogue was awkward",
    "the characters were memorable",
    "the movie was emotional but the script was weak",
    "this movie was beautifully acted and emotionally powerful and the story remained engaging throughout",
    "the film was boring and badly written and the ending was disappointing",
    "the movie was released in 2020 and includes several main characters"
]

# Custom inference strings are forcefully pipelined through the exact same 
# mathematical sanitization and tokenization stages to ensure compatibility.
custom_reviews_clean = [clean_text(text) for text in custom_reviews]
custom_seq = tokenizer.texts_to_sequences(custom_reviews_clean)
custom_pad = tf.keras.preprocessing.sequence.pad_sequences(
    custom_seq, maxlen=max_length, padding="post", truncating="post"
)

predictions = model.predict(custom_pad, verbose=0)

print("\n[PREVIEW] Custom Target Classifications:")
for review, probs in zip(custom_reviews, predictions):
    predicted_index = int(np.argmax(probs))
    predicted_label = index_to_label[predicted_index]
    confidence = float(probs[predicted_index])

    negative_prob = float(probs[0])
    positive_prob = float(probs[1])
    mixed_prob = float(probs[2])
    neutral_prob = float(probs[3])

    print(f'\nReview text : "{review}"')
    print(f'Prediction : {predicted_label.upper()} (Confidence: {confidence:.4f})')
    print(f'Probability Matrix -> NEG: {negative_prob:.2f} | POS: {positive_prob:.2f} | MIXED: {mixed_prob:.2f} | NEUT: {neutral_prob:.2f}')
    print("-" * 60)

# ==========================================
# PHASE 10: ARTIFACT SERIALIZATION
# ==========================================
print("\n[INFO] Serializing trained model artifacts and vocabulary tokenizer to disk...")

# The fully trained artifacts are serialized. The .keras format encapsulates internal weights 
# and geometric architecture, while the tokenizer JSON retains the exact vocab mapping.
model_save_path = os.path.join(final_dataset_folder, "sentiment_classifier.keras")
tokenizer_save_path = os.path.join(final_dataset_folder, "tokenizer_config.json")

model.save(model_save_path)

tokenizer_json = tokenizer.to_json()
with open(tokenizer_save_path, "w", encoding="utf-8") as f:
    f.write(tokenizer_json)

print("\n" + "="*65)
print(" EXECUTIVE SUMMARY: DEEP LEARNING PIPELINE COMPLETED")
print("="*65)
print(f"|-- Model Exported     : .\\{os.path.relpath(model_save_path, project_folder)}")
print(f"|-- Tokenizer Exported : .\\{os.path.relpath(tokenizer_save_path, project_folder)}")
print("="*65 + "\n")